### ISSUE TITLE
Usability Issue: raw post ids / times visible in the app.

### ISSUE THREAD

**Issue by jacobe90** [amandeepksingh/WildWhere#57]
In the main map UI, and the UI that lists posts, the raw ids of the posts are visible. Also, the full unformatted time of posts is listed (consider just using the day, hour, minute, and formatting this nicely). Finally, there are a large number of significant figures in the lat/lon of a sighting (this also looks unprocessed). From a user perspective, this is confusing, and not necessary to see in the app.

**Comment by jcbeaumont22** [comment]
Fixed
